### ISSUE TITLE
Cannot connect to postgres database.

### ISSUE THREAD

**Issue by thedodd** [jaemk/migrant#16]
Unable to connect to my Postgres instance using migrant.
```
Error: ConfigError: Cannot connect to postgres database with connection string: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=require". Do the database & user exist?
```

This is probably due to the fact that the instance is setup with a self-signed cert. Depending on the TLS backend being used by this tool, cert verification will need to be disabled when `sslmode=require`. 

Happy to provide any additional information if needed.

**Comment by jaemk** [comment]
The connection handling happens in `migrant_lib` here https://github.com/jaemk/migrant_lib/blob/c03841f7d502198717ef7810c5be370a88f54e31/src/drivers/pg.rs#L121 . According to the postgres docs (https://github.com/jaemk/migrant_lib/blob/c03841f7d502198717ef7810c5be370a88f54e31/src/drivers/pg.rs#L121), it looks like we'll need to be smarter about supporting tls in general, and specifically allow passing in a tls-connector as shown in the postgres-openssl and postgres_native_tls examples https://docs.rs/postgres-openssl/0.3.0/postgres_openssl/ https://docs.rs/postgres-native-tls/0.3.0/postgres_native_tls/ .

I'm going to make an issue in migrant_lib since that's where the update needs to live

**Comment by jaemk** [comment]
I've now just run into this myself so I'll see what I can do

**Comment by jaemk** [comment]
added in `0.14.0` - as noted in the migrant_lib readme, when the `postgres` feature (or `d-postgres` in migrant_lib) is specified, the `ssl_cert_file = "..."` value in your `Migrant.toml` will be used to build a tls connection using rustls
